// GENERATED by ecs-truly-auto-mode from .ecs-auto-mode/manifest.yaml
// Controlled by: pipeline
//
// The CodePipeline target. Implements the same deployment contract as the GitHub
// Actions workflow — see references/pipeline/contract.md — so that for a given
// commit both produce the same image tag and the same service stack change.
//
// This lives in the platform stack: the pipeline itself is infrastructure that
// changes rarely, even though what it deploys changes constantly.

import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as codepipeline from 'aws-cdk-lib/aws-codepipeline';
import * as actions from 'aws-cdk-lib/aws-codepipeline-actions';
import * as codebuild from 'aws-cdk-lib/aws-codebuild';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as iam from 'aws-cdk-lib/aws-iam';
import { deployPolicyStatements, DeployPermissionsProps } from './deploy-permissions';

export interface CodePipelineTargetProps extends DeployPermissionsProps {
  /**
   * A CodeConnections connection already in AVAILABLE status. It cannot be created
   * here: a new connection starts in PENDING and requires a human to finish an OAuth
   * handshake in the console, which CloudFormation cannot do.
   */
  readonly connectionArn: string;
  /** owner/repo */
  readonly repository: string;
  readonly branch: string;
  readonly dockerfile: string;
  readonly buildContext: string;
  /** linux/arm64 or linux/amd64 — must match the image the task expects. */
  readonly dockerPlatform: string;
  readonly repositoryUri: string;
  readonly loadBalanced: boolean;
  /** Globs from the manifest; CodePipeline filters the trigger on these. */
  readonly pathFilter: string[];
}

export class CodePipelineTarget extends Construct {
  constructor(scope: Construct, id: string, props: CodePipelineTargetProps) {
    super(scope, id);

    const artifactBucket = new s3.Bucket(this, 'ArtifactBucket', {
      encryption: s3.BucketEncryption.S3_MANAGED,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
      lifecycleRules: [{ expiration: cdk.Duration.days(30) }],
    });

    const project = new codebuild.PipelineProject(this, 'Build', {
      projectName: `${props.appName}-build-deploy`,
      environment: {
        buildImage: codebuild.LinuxBuildImage.STANDARD_7_0,
        // Required to run docker build.
        privileged: true,
        computeType: codebuild.ComputeType.SMALL,
      },
      environmentVariables: {
        AWS_REGION: { value: props.region },
        SSM_PREFIX: { value: props.ssmPrefix },
        REPOSITORY_URI: { value: props.repositoryUri },
        SERVICE_STACK: { value: `${props.appName}-service` },
        SERVICE_NAME: { value: props.appName },
      },
      buildSpec: codebuild.BuildSpec.fromObject(
        this.buildSpec(props),
      ),
      timeout: cdk.Duration.minutes(30),
    });

    for (const statement of deployPolicyStatements(props)) {
      project.addToRolePolicy(statement);
    }
    // Reading the cluster name back for the stabilize step.
    project.addToRolePolicy(
      new iam.PolicyStatement({
        actions: ['ecs:DescribeServices'],
        resources: [`arn:aws:ecs:${props.region}:${props.account}:service/${props.clusterName}/${props.appName}`],
      }),
    );

    const source = new codepipeline.Artifact('Source');
    const sourceAction = new actions.CodeStarConnectionsSourceAction({
      actionName: 'Source',
      owner: props.repository.split('/')[0],
      repo: props.repository.split('/')[1],
      branch: props.branch,
      connectionArn: props.connectionArn,
      output: source,
      // Path filtering is done by the V2 trigger below, which is the only place it
      // can be expressed. Leaving push-triggering on here as well would run the
      // pipeline for every push regardless of the filter.
      triggerOnPush: false,
    });

    new codepipeline.Pipeline(this, 'Pipeline', {
      pipelineName: `${props.appName}-deploy`,
      artifactBucket,
      pipelineType: codepipeline.PipelineType.V2,
      // Serialize: two concurrent rollouts of the same service race on the ECS
      // deployment and the loser's tasks get replaced mid-rollout.
      executionMode: codepipeline.ExecutionMode.QUEUED,
      restartExecutionOnUpdate: false,
      stages: [
        { stageName: 'Source', actions: [sourceAction] },
        {
          stageName: 'BuildAndDeploy',
          actions: [
            new actions.CodeBuildAction({
              actionName: 'BuildAndDeploy',
              project,
              input: source,
            }),
          ],
        },
      ],
      triggers: [
        {
          providerType: codepipeline.ProviderType.CODE_STAR_SOURCE_CONNECTION,
          gitConfiguration: {
            sourceAction,
            pushFilter: [
              {
                branchesIncludes: [props.branch],
                filePathsIncludes: props.pathFilter,
              },
            ],
          },
        },
      ],
    });
  }

  /**
   * The contract's steps, in order. Deliberately mirrors the GitHub Actions
   * workflow step for step — if one changes, both change.
   */
  private buildSpec(props: CodePipelineTargetProps): Record<string, unknown> {
    return {
      version: '0.2',
      phases: {
        pre_build: {
          commands: [
            'echo "--- Authenticate to ECR ---"',
            'aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "${REPOSITORY_URI%%/*}"',
            // The image tag is the full commit SHA, never `latest`. A mutable tag
            // would leave the service stack template unchanged between deploys, so
            // CloudFormation would see no change and the rollout would not happen.
            'export IMAGE_TAG="$CODEBUILD_RESOLVED_SOURCE_VERSION"',
            'echo "Image tag: $IMAGE_TAG"',
          ],
        },
        build: {
          commands: [
            'echo "--- Build and push ---"',
            `docker build --platform ${props.dockerPlatform} -f ${props.dockerfile} -t "$REPOSITORY_URI:$IMAGE_TAG" ${props.buildContext}`,
            'docker push "$REPOSITORY_URI:$IMAGE_TAG"',
          ],
        },
        post_build: {
          commands: [
            'echo "--- Preflight platform parameters ---"',
            'chmod +x infra/scripts/ssm-preflight.sh',
            `./infra/scripts/ssm-preflight.sh "$SSM_PREFIX" "$AWS_REGION" ${props.loadBalanced ? '--load-balanced' : ''}`,

            'echo "--- Deploy service stack ---"',
            'cd infra && npm ci',
            'npx cdk deploy "$SERVICE_STACK" --parameters "ImageTag=$IMAGE_TAG" --require-approval never --progress events',
            'cd ..',

            'echo "--- Wait for steady state ---"',
            // A deploy that reports success while tasks crash-loop is worse than a
            // failed deploy, because nobody looks at it.
            'CLUSTER="$(aws ssm get-parameter --name "$SSM_PREFIX/cluster-name" --region "$AWS_REGION" --query Parameter.Value --output text)"',
            'aws ecs wait services-stable --cluster "$CLUSTER" --services "$SERVICE_NAME" --region "$AWS_REGION"',
          ],
        },
      },
      cache: { paths: ['/root/.npm/**/*'] },
    };
  }
}
