// GENERATED by ecs-truly-auto-mode from .ecs-auto-mode/manifest.yaml
// Controlled by: (whole manifest)
//
// This file is the concrete, typed projection of the manifest. The stacks read it
// and nothing else, which is what keeps `cdk synth` hermetic — no AWS lookups, no
// cdk.context.json, no credentials required.
//
// Edit the manifest and re-run the skill rather than editing this file. The skill
// detects edits here and will ask before overwriting.

export type Architecture = 'ARM64' | 'X86_64';
export type EgressClassification = 'none' | 'public';

/**
 * AWS services the workload calls, used to decide which VPC endpoints exist.
 * `s3` is always present in isolated mode: ECR stores image layers in S3, so a task
 * cannot pull its image without the gateway endpoint.
 */
export type AwsServiceKey =
  | 'ecr' | 'ecr-docker' | 'logs' | 'secretsmanager' | 'ssm'
  | 's3' | 'dynamodb' | 'sqs' | 'sns' | 'kms' | 'sts' | 'events';

/**
 * Networking is either created or imported from explicit attributes. There is
 * deliberately no "look it up" variant — `Vpc.fromLookup` would require credentials
 * at synth time and write a cdk.context.json that goes stale.
 */
export type NetworkConfig =
  | {
      readonly mode: 'create';
      /**
       * Explicit AZ names, two minimum — an ALB requires two.
       *
       * These are recorded during planning rather than discovered at synth on
       * purpose. `maxAzs` makes the CDK resolve the account's AZ list through a
       * context lookup, which needs credentials and writes a cdk.context.json that
       * goes stale. Naming them here keeps synth offline and deterministic.
       */
      readonly availabilityZones: string[];
    }
  | {
      readonly mode: 'adopt';
      readonly vpcId: string;
      readonly availabilityZones: string[];
      readonly isolatedSubnetIds?: string[];
      readonly privateSubnetIds?: string[];
      readonly publicSubnetIds?: string[];
    };

/** A resource that is either created here or imported by identifier. */
export type Adoptable<T> = { readonly mode: 'create' } | ({ readonly mode: 'adopt' } & T);

export interface PublicHostname {
  readonly hostname: string;
  readonly certificateArn: string;
  readonly hostedZoneId: string;
  readonly zoneName: string;
}

/** A network-reached datastore: needs a security group rule, not IAM. */
export interface NetworkDatastore {
  readonly id: string;
  readonly kind: 'rds' | 'elasticache' | 'documentdb';
  readonly securityGroupId: string;
  readonly port: number;
  readonly endpointAddress: string;
}

/** An API-reached datastore: needs task-role permissions, not a security group rule. */
export interface ApiDatastore {
  readonly id: string;
  readonly kind: 'dynamodb' | 's3' | 'sqs' | 'sns';
  /** Exact resource ARNs. Never a wildcard — uncertainty belongs in the plan, not the policy. */
  readonly resourceArns: string[];
  readonly actions: string[];
}

export interface SecretRef {
  /** Environment variable name the container reads. */
  readonly name: string;
  readonly source: 'secretsmanager' | 'ssm';
  /** ARN of the secret, or the SSM parameter name. A pointer — never a value. */
  readonly arn: string;
  /** Key within a JSON-valued Secrets Manager secret. */
  readonly jsonKey?: string;
  /** Customer-managed KMS key, if the secret uses one. The execution role needs kms:Decrypt. */
  readonly kmsKeyArn?: string;
}

export interface HealthCheckConfig {
  readonly type: 'http' | 'tcp';
  /** Present only when type is 'http'. */
  readonly path?: string;
  readonly healthyThresholdCount?: number;
  readonly interval?: number;
}

export interface ServiceSizing {
  readonly cpu: number;
  readonly memoryLimitMiB: number;
  readonly desiredCount: number;
}

export interface AppConfig {
  readonly name: string;
  readonly env: { readonly account: string; readonly region: string };
  /** SSM path prefix carrying the platform → service contract. */
  readonly ssmPrefix: string;
  /**
   * The target account's CDK bootstrap qualifier — `hnb659fds` unless the account
   * was bootstrapped with `cdk bootstrap --qualifier <value>`. Names the bootstrap
   * roles the deploy role is granted `sts:AssumeRole` on; see deploy-permissions.ts.
   */
  readonly cdkQualifier: string;

  readonly architecture: Architecture;
  readonly containerPort: number;
  readonly healthCheck: HealthCheckConfig;
  readonly sizing: ServiceSizing;

  /**
   * Decides subnet placement and whether a NAT gateway exists. Derived from the
   * egress analysis, never defaulted — see references/analysis/egress.md.
   */
  readonly egress: EgressClassification;
  readonly awsServices: AwsServiceKey[];

  readonly network: NetworkConfig;
  readonly cluster: Adoptable<{ clusterName: string }>;
  readonly repository: Adoptable<{ repositoryName: string }>;
  readonly logGroup: Adoptable<{ logGroupName: string }>;
  readonly logRetentionDays: number;

  /** Absent when the service takes no inbound traffic. */
  readonly loadBalancer?: Adoptable<{
    loadBalancerArn: string;
    securityGroupId: string;
    listenerArn: string;
    /** Required when adopting a shared listener, or it hijacks other traffic. */
    listenerRuleHostHeader?: string;
  }>;

  readonly publicHostname?: PublicHostname;

  readonly networkDatastores: NetworkDatastore[];
  readonly apiDatastores: ApiDatastore[];

  readonly environment: Record<string, string>;
  readonly secrets: SecretRef[];
}

/**
 * The pipeline's own shape — kept separate from `AppConfig`, which is a pure
 * projection of the resource plan. `bin/app.ts` reads this to decide whether the
 * platform stack needs the GitHub OIDC role.
 */
export type PipelineConfig =
  | { readonly target: 'github-actions'; readonly branch: string; readonly repository: string }
  | { readonly target: 'codepipeline'; readonly branch: string };
