// GENERATED by ecs-truly-auto-mode from .ecs-auto-mode/manifest.yaml
// Controlled by: pipeline
//
// The least-privilege policy shared by both pipeline targets, plus the GitHub OIDC
// role that carries it.
//
// Scoped to the ECR repository, the SSM prefix, and the *service* stack only. The
// platform stack is deliberately excluded: the pipeline has no reason to modify
// networking or IAM, and not granting it means a compromised pipeline cannot.

import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as iam from 'aws-cdk-lib/aws-iam';

export interface DeployPermissionsProps {
  readonly appName: string;
  readonly account: string;
  readonly region: string;
  readonly ssmPrefix: string;
  readonly repositoryArn: string;
  readonly taskRoleArn: string;
  readonly executionRoleArn: string;
  readonly clusterName: string;
}

/**
 * Exactly what the deployment contract's steps require, and nothing else.
 */
export function deployPolicyStatements(props: DeployPermissionsProps): iam.PolicyStatement[] {
  const { account, region, appName, ssmPrefix } = props;

  return [
    // Takes no resource — the API is account-wide by design.
    new iam.PolicyStatement({
      sid: 'EcrAuth',
      actions: ['ecr:GetAuthorizationToken'],
      resources: ['*'],
    }),

    new iam.PolicyStatement({
      sid: 'EcrPush',
      actions: [
        'ecr:BatchCheckLayerAvailability',
        'ecr:InitiateLayerUpload',
        'ecr:UploadLayerPart',
        'ecr:CompleteLayerUpload',
        'ecr:PutImage',
        'ecr:BatchGetImage',
        'ecr:DescribeImages',
      ],
      resources: [props.repositoryArn],
    }),

    // The preflight step, and the service stack's own parameter resolution.
    new iam.PolicyStatement({
      sid: 'SsmRead',
      actions: ['ssm:GetParameter', 'ssm:GetParameters'],
      resources: [
        cdk.Arn.format({
          partition: 'aws',
          service: 'ssm',
          region,
          account,
          resource: 'parameter',
          resourceName: `${ssmPrefix.replace(/^\//, '')}/*`,
        }),
      ],
    }),

    // The service stack only. Note the absence of `${appName}-platform`.
    new iam.PolicyStatement({
      sid: 'DeployServiceStackOnly',
      actions: [
        'cloudformation:CreateStack',
        'cloudformation:UpdateStack',
        'cloudformation:DescribeStacks',
        'cloudformation:DescribeStackEvents',
        'cloudformation:DescribeStackResources',
        'cloudformation:GetTemplate',
        'cloudformation:CreateChangeSet',
        'cloudformation:DescribeChangeSet',
        'cloudformation:ExecuteChangeSet',
        'cloudformation:DeleteChangeSet',
        'cloudformation:GetTemplateSummary',
      ],
      resources: [
        `arn:aws:cloudformation:${region}:${account}:stack/${appName}-service/*`,
      ],
    }),

    new iam.PolicyStatement({
      sid: 'EcsDeploy',
      actions: [
        'ecs:RegisterTaskDefinition',
        'ecs:DeregisterTaskDefinition',
        'ecs:DescribeTaskDefinition',
      ],
      // These APIs are not resource-scopable; task definitions have no ARN at
      // registration time.
      resources: ['*'],
    }),

    new iam.PolicyStatement({
      sid: 'EcsService',
      actions: ['ecs:UpdateService', 'ecs:DescribeServices', 'ecs:CreateService', 'ecs:TagResource'],
      resources: [
        `arn:aws:ecs:${region}:${account}:service/${props.clusterName}/${appName}`,
      ],
    }),

    // The escalation path worth scoping carefully. Unscoped, this lets the pipeline
    // hand ECS *any* role in the account.
    new iam.PolicyStatement({
      sid: 'PassTaskRolesOnly',
      actions: ['iam:PassRole'],
      resources: [props.taskRoleArn, props.executionRoleArn],
      conditions: { StringEquals: { 'iam:PassedToService': 'ecs-tasks.amazonaws.com' } },
    }),

    // The CDK CLI reads the bootstrap version parameter before deploying.
    new iam.PolicyStatement({
      sid: 'CdkBootstrapRead',
      actions: ['ssm:GetParameter'],
      resources: [`arn:aws:ssm:${region}:${account}:parameter/cdk-bootstrap/*`],
    }),
  ];
}

export interface GitHubOidcRoleProps extends DeployPermissionsProps {
  /** owner/repo — scopes the trust policy. */
  readonly repository: string;
  readonly branch: string;
  /** Set when the account already has a GitHub OIDC provider; creating a second fails. */
  readonly existingProviderArn?: string;
}

export class GitHubOidcRole extends Construct {
  public readonly role: iam.Role;

  constructor(scope: Construct, id: string, props: GitHubOidcRoleProps) {
    super(scope, id);

    const providerArn =
      props.existingProviderArn ??
      new iam.OpenIdConnectProvider(this, 'Provider', {
        url: 'https://token.actions.githubusercontent.com',
        clientIds: ['sts.amazonaws.com'],
      }).openIdConnectProviderArn;

    const provider = iam.OpenIdConnectProvider.fromOpenIdConnectProviderArn(
      this,
      'ImportedProvider',
      providerArn,
    );

    this.role = new iam.Role(this, 'Role', {
      roleName: `${props.appName}-deploy`,
      description: `GitHub Actions deploy role for ${props.repository}`,
      // The `sub` condition is what makes this safe. A trust policy that accepts the
      // GitHub OIDC provider without one can be assumed from ANY repository on
      // GitHub — a full account compromise, not a misconfiguration.
      assumedBy: new iam.WebIdentityPrincipal(provider.openIdConnectProviderArn, {
        StringEquals: {
          'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com',
        },
        StringLike: {
          'token.actions.githubusercontent.com:sub': `repo:${props.repository}:*`,
        },
      }),
      maxSessionDuration: cdk.Duration.hours(1),
    });

    for (const statement of deployPolicyStatements(props)) {
      this.role.addToPolicy(statement);
    }
  }
}
