// GENERATED by ecs-truly-auto-mode from .ecs-auto-mode/manifest.yaml
// Controlled by: plan.resources, analysis.egress
//
// The platform stack. Everything here changes rarely — networking, the cluster, the
// registry, load balancing, roles, logging, DNS. Routine deploys touch the *service*
// stack instead, which is why the two are separate.
//
// This stack publishes everything the service stack needs to SSM Parameter Store.
// It deliberately does not use CloudFormation exports: Fn::ImportValue would lock
// this stack against changes while the service stack imported from it, which is
// exactly the wrong coupling between a rarely-changing stack and a constantly-
// changing one.

import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ecs from 'aws-cdk-lib/aws-ecs';
import * as ecr from 'aws-cdk-lib/aws-ecr';
import * as elbv2 from 'aws-cdk-lib/aws-elasticloadbalancingv2';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as ssm from 'aws-cdk-lib/aws-ssm';
import * as acm from 'aws-cdk-lib/aws-certificatemanager';
import * as route53 from 'aws-cdk-lib/aws-route53';
import * as targets from 'aws-cdk-lib/aws-route53-targets';
import { AppConfig, AwsServiceKey } from './config';
import { GitHubOidcRole } from './deploy-permissions';

export interface PlatformStackGitHubActions {
  readonly repository: string;
  readonly branch: string;
  /** Set when the account already has a GitHub OIDC provider; creating a second fails. */
  readonly existingProviderArn?: string;
}

export interface PlatformStackProps extends cdk.StackProps {
  readonly config: AppConfig;
  /**
   * Present only when the recorded pipeline target is `github-actions`. Wires the
   * GitHub OIDC-trusted deploy role into this stack, using the task role, execution
   * role, cluster and repository already constructed here — see deploy-permissions.ts.
   * Absent for `codepipeline`, which authenticates through a CodeStar connection
   * instead.
   */
  readonly githubActions?: PlatformStackGitHubActions;
}

export class PlatformStack extends cdk.Stack {
  public readonly vpc: ec2.IVpc;
  public readonly cluster: ecs.ICluster;
  public readonly repository: ecr.IRepository;

  private readonly config: AppConfig;
  private readonly githubActions?: PlatformStackGitHubActions;

  /**
   * Serving AZs from config rather than the default implementation is what keeps
   * synth offline. The base implementation performs a context lookup against the
   * target account, which fails outright without credentials — and a pipeline that
   * synthesizes this stack should not need them.
   */
  public get availabilityZones(): string[] {
    return this.config.network.mode === 'create'
      ? this.config.network.availabilityZones
      : this.config.network.availabilityZones;
  }

  constructor(scope: Construct, id: string, props: PlatformStackProps) {
    super(scope, id, props);
    const config = (this.config = props.config);
    this.githubActions = props.githubActions;

    this.vpc = this.buildVpc();

    // Isolated placement means no NAT, so every AWS call the task makes has to go
    // through a VPC endpoint. See references/analysis/egress.md for why this is the
    // decision worth getting right.
    if (config.egress === 'none') {
      this.addVpcEndpoints(this.vpc);
    }

    this.cluster = this.buildCluster(this.vpc);
    this.repository = this.buildRepository();

    const logGroup = this.buildLogGroup();
    const taskSecurityGroup = this.buildTaskSecurityGroup(this.vpc);

    this.wireNetworkDatastores(taskSecurityGroup);

    const executionRole = this.buildExecutionRole();
    const taskRole = this.buildTaskRole();

    const targetGroup = config.loadBalancer
      ? this.buildLoadBalancing(this.vpc, taskSecurityGroup)
      : undefined;

    this.buildGitHubOidcRole({ taskRole, executionRole });

    this.publishParameters({ logGroup, taskSecurityGroup, executionRole, taskRole, targetGroup });
  }

  // ---------------------------------------------------------------- networking

  /**
   * Subnet layout follows the egress classification. An isolated workload gets no
   * NAT gateway at all, which is the single largest standing cost this tool avoids.
   */
  private buildVpc(): ec2.IVpc {
    const { network, egress } = this.config;

    if (network.mode === 'adopt') {
      // Route tables belong to whoever owns the adopted VPC; this stack only places
      // resources into the subnets and never inspects their routing.
      cdk.Annotations.of(this).acknowledgeWarning(
        '@aws-cdk/aws-ec2:noSubnetRouteTableId',
        'Adopted subnets are used for placement only; their routing is not managed here',
      );
      // Explicit attributes, never fromLookup — synth must work without credentials.
      return ec2.Vpc.fromVpcAttributes(this, 'Vpc', {
        vpcId: network.vpcId,
        availabilityZones: network.availabilityZones,
        isolatedSubnetIds: network.isolatedSubnetIds,
        privateSubnetIds: network.privateSubnetIds,
        publicSubnetIds: network.publicSubnetIds,
      });
    }

    const appSubnet: ec2.SubnetConfiguration =
      egress === 'none'
        ? { name: 'app', subnetType: ec2.SubnetType.PRIVATE_ISOLATED, cidrMask: 22 }
        : { name: 'app', subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS, cidrMask: 22 };

    return new ec2.Vpc(this, 'Vpc', {
      availabilityZones: network.availabilityZones,
      // Zero NAT gateways when nothing needs to reach the internet.
      natGateways: egress === 'none' ? 0 : network.availabilityZones.length,
      subnetConfiguration: [
        { name: 'public', subnetType: ec2.SubnetType.PUBLIC, cidrMask: 24 },
        appSubnet,
      ],
    });
  }

  /** The subnets tasks and endpoints live in, derived from the egress classification. */
  private get appSubnets(): ec2.SubnetSelection {
    return {
      subnetType:
        this.config.egress === 'none'
          ? ec2.SubnetType.PRIVATE_ISOLATED
          : ec2.SubnetType.PRIVATE_WITH_EGRESS,
    };
  }

  /**
   * Interface endpoints for exactly the services the analysis found, plus the two
   * gateway endpoints. Endpoints are not free — an interface endpoint bills hourly
   * per AZ — so this provisions what is used rather than everything available.
   */
  private addVpcEndpoints(vpc: ec2.IVpc): void {
    const endpointSg = new ec2.SecurityGroup(this, 'EndpointSecurityGroup', {
      vpc,
      description: 'Allows tasks to reach VPC interface endpoints over 443',
      allowAllOutbound: false,
    });
    endpointSg.addIngressRule(
      ec2.Peer.ipv4(vpc.vpcCidrBlock),
      ec2.Port.tcp(443),
      'HTTPS from within the VPC',
    );

    const interfaceServices: Partial<Record<AwsServiceKey, ec2.InterfaceVpcEndpointAwsService>> = {
      ecr: ec2.InterfaceVpcEndpointAwsService.ECR,
      'ecr-docker': ec2.InterfaceVpcEndpointAwsService.ECR_DOCKER,
      logs: ec2.InterfaceVpcEndpointAwsService.CLOUDWATCH_LOGS,
      secretsmanager: ec2.InterfaceVpcEndpointAwsService.SECRETS_MANAGER,
      ssm: ec2.InterfaceVpcEndpointAwsService.SSM,
      sqs: ec2.InterfaceVpcEndpointAwsService.SQS,
      sns: ec2.InterfaceVpcEndpointAwsService.SNS,
      kms: ec2.InterfaceVpcEndpointAwsService.KMS,
      sts: ec2.InterfaceVpcEndpointAwsService.STS,
      events: ec2.InterfaceVpcEndpointAwsService.EVENTBRIDGE,
    };

    for (const key of this.config.awsServices) {
      const service = interfaceServices[key];
      if (!service) continue; // s3 and dynamodb are gateway endpoints, handled below
      new ec2.InterfaceVpcEndpoint(this, `Endpoint${pascal(key)}`, {
        vpc,
        service,
        subnets: this.appSubnets,
        securityGroups: [endpointSg],
        // Without private DNS the SDK still resolves the public endpoint and hangs.
        privateDnsEnabled: true,
      });
    }

    // Always present: ECR stores image layers in S3, so a task in isolated subnets
    // cannot pull its image without this — and the resulting error never mentions S3.
    new ec2.GatewayVpcEndpoint(this, 'EndpointS3', {
      vpc,
      service: ec2.GatewayVpcEndpointAwsService.S3,
      subnets: [this.appSubnets],
    });

    if (this.config.awsServices.includes('dynamodb')) {
      new ec2.GatewayVpcEndpoint(this, 'EndpointDynamoDb', {
        vpc,
        service: ec2.GatewayVpcEndpointAwsService.DYNAMODB,
        subnets: [this.appSubnets],
      });
    }
  }

  // ------------------------------------------------------------------- compute

  private buildCluster(vpc: ec2.IVpc): ecs.ICluster {
    const { cluster } = this.config;
    if (cluster.mode === 'adopt') {
      return ecs.Cluster.fromClusterAttributes(this, 'Cluster', {
        clusterName: cluster.clusterName,
        vpc,
        securityGroups: [],
      });
    }
    // Container Insights is deliberately not enabled here. It is genuinely useful,
    // but it bills per metric and this tool does not turn on standing costs the user
    // did not ask for. Enable it explicitly if you want it.
    return new ecs.Cluster(this, 'Cluster', {
      vpc,
      clusterName: `${this.config.name}-cluster`,
    });
  }

  private buildRepository(): ecr.IRepository {
    const { repository } = this.config;
    if (repository.mode === 'adopt') {
      return ecr.Repository.fromRepositoryName(this, 'Repository', repository.repositoryName);
    }
    return new ecr.Repository(this, 'Repository', {
      repositoryName: this.config.name,
      imageScanOnPush: true,
      // Unbounded image retention is a slow, invisible storage cost.
      lifecycleRules: [{ maxImageCount: 20, description: 'Retain the last 20 images' }],
    });
  }

  private buildLogGroup(): logs.ILogGroup {
    const { logGroup } = this.config;
    if (logGroup.mode === 'adopt') {
      return logs.LogGroup.fromLogGroupName(this, 'LogGroup', logGroup.logGroupName);
    }
    return new logs.LogGroup(this, 'LogGroup', {
      logGroupName: `/ecs/${this.config.name}`,
      // The CDK default is infinite retention, which is a real and permanent cost.
      retention: retentionDays(this.config.logRetentionDays),
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });
  }

  // ------------------------------------------------------------------ security

  private buildTaskSecurityGroup(vpc: ec2.IVpc): ec2.SecurityGroup {
    return new ec2.SecurityGroup(this, 'TaskSecurityGroup', {
      vpc,
      description: `Tasks for ${this.config.name}`,
      allowAllOutbound: true,
    });
  }

  /**
   * Network-reached datastores need an ingress rule on *their* security group,
   * allowing the task group in. This is the piece most often missed, and it fails
   * as a connection timeout at startup rather than a clear permission error.
   */
  private wireNetworkDatastores(taskSg: ec2.ISecurityGroup): void {
    for (const store of this.config.networkDatastores) {
      const storeSg = ec2.SecurityGroup.fromSecurityGroupId(
        this,
        `DatastoreSg${pascal(store.id)}`,
        store.securityGroupId,
        // The datastore's security group is not ours to own or mutate wholesale.
        { mutable: true },
      );
      storeSg.addIngressRule(
        taskSg,
        ec2.Port.tcp(store.port),
        // Restricted charset — see the note on the load balancer rule below.
        `${this.config.name} tasks to ${store.id}`,
      );
    }
  }

  private buildExecutionRole(): iam.IRole {
    const role = new iam.Role(this, 'ExecutionRole', {
      assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),
      description: `Pulls the image and injects secrets for ${this.config.name}`,
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AmazonECSTaskExecutionRolePolicy'),
      ],
    });

    // Secrets are injected by the ECS agent before the container starts, so this is
    // the *execution* role's job, not the task role's. Granting the task role
    // instead produces a task that fails to start, naming a role that looks right.
    const secretArns = this.config.secrets.filter((s) => s.source === 'secretsmanager').map((s) => s.arn);
    if (secretArns.length > 0) {
      role.addToPrincipalPolicy(
        new iam.PolicyStatement({
          actions: ['secretsmanager:GetSecretValue'],
          resources: secretArns,
        }),
      );
    }

    const parameterNames = this.config.secrets.filter((s) => s.source === 'ssm').map((s) => s.arn);
    if (parameterNames.length > 0) {
      role.addToPrincipalPolicy(
        new iam.PolicyStatement({
          actions: ['ssm:GetParameters'],
          resources: parameterNames.map((name) =>
            name.startsWith('arn:')
              ? name
              : cdk.Arn.format({ service: 'ssm', resource: 'parameter', resourceName: name.replace(/^\//, '') }, this),
          ),
        }),
      );
    }

    const kmsKeys = [...new Set(this.config.secrets.map((s) => s.kmsKeyArn).filter(Boolean))] as string[];
    if (kmsKeys.length > 0) {
      role.addToPrincipalPolicy(
        new iam.PolicyStatement({ actions: ['kms:Decrypt'], resources: kmsKeys }),
      );
    }

    return role;
  }

  /**
   * The task role carries only what the application code was found to use, scoped to
   * the exact resources in the plan. Wildcards would make the analysis's uncertainty
   * permanent and invisible.
   */
  private buildTaskRole(): iam.IRole {
    const role = new iam.Role(this, 'TaskRole', {
      assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),
      description: `Application permissions for ${this.config.name}`,
    });

    for (const store of this.config.apiDatastores) {
      role.addToPrincipalPolicy(
        new iam.PolicyStatement({
          sid: `${pascal(store.id)}Access`,
          actions: store.actions,
          resources: store.resourceArns,
        }),
      );
    }

    return role;
  }

  // ------------------------------------------------------------------- ingress

  /**
   * The target group lives here, not in the service stack, precisely because it
   * holds the health check configuration — putting it in the service stack would
   * mean every routine deploy replaced the target group and its listener rule.
   */
  private buildLoadBalancing(vpc: ec2.IVpc, taskSg: ec2.SecurityGroup): elbv2.IApplicationTargetGroup {
    const lbConfig = this.config.loadBalancer!;
    const internetFacing = this.config.publicHostname !== undefined;

    let listener: elbv2.IApplicationListener;
    let albSecurityGroup: ec2.ISecurityGroup;

    if (lbConfig.mode === 'adopt') {
      albSecurityGroup = ec2.SecurityGroup.fromSecurityGroupId(
        this,
        'AlbSecurityGroup',
        lbConfig.securityGroupId,
      );
      listener = elbv2.ApplicationListener.fromApplicationListenerAttributes(this, 'Listener', {
        listenerArn: lbConfig.listenerArn,
        securityGroup: albSecurityGroup,
      });
    } else {
      const alb = new elbv2.ApplicationLoadBalancer(this, 'LoadBalancer', {
        vpc,
        internetFacing,
        vpcSubnets: internetFacing ? { subnetType: ec2.SubnetType.PUBLIC } : this.appSubnets,
      });
      albSecurityGroup = alb.connections.securityGroups[0];

      if (this.config.publicHostname) {
        const certificate = acm.Certificate.fromCertificateArn(
          this,
          'Certificate',
          this.config.publicHostname.certificateArn,
        );
        listener = alb.addListener('HttpsListener', {
          port: 443,
          certificates: [certificate],
          open: true,
        });
        // Redirect rather than serving plaintext on 80.
        alb.addListener('HttpRedirect', {
          port: 80,
          open: true,
          defaultAction: elbv2.ListenerAction.redirect({ protocol: 'HTTPS', port: '443', permanent: true }),
        });
        this.buildDnsRecord(alb);
      } else {
        listener = alb.addListener('HttpListener', { port: 80, open: true });
      }
    }

    // Both directions have to be wired explicitly here.
    //
    // Normally CDK adds the load balancer's *egress* rule as a side effect of
    // registering a target. This design registers the target in the service stack
    // instead, so that never happens — and the result is a service whose tasks start
    // cleanly, fail every health check, and get SIGKILLed with exit code 137. The
    // logs show the app listening happily, which makes it look like an application
    // problem rather than a missing security group rule.
    //
    // EC2 restricts rule descriptions to `a-zA-Z0-9. _-:/()#,@[]+=&;{}!$*` — no
    // arrows, no angle brackets. That only fails at the API; synth and cfn-lint
    // both accept them.
    const containerPort = ec2.Port.tcp(this.config.containerPort);

    // Tasks accept traffic from the load balancer only — never from a CIDR.
    taskSg.addIngressRule(albSecurityGroup, containerPort, 'Load balancer to tasks');

    if (lbConfig.mode === 'create') {
      albSecurityGroup.addEgressRule(taskSg, containerPort, 'Load balancer to tasks');
    } else {
      // An imported security group is immutable, so the rule cannot be added here.
      cdk.Annotations.of(this).addWarningV2(
        'ecs-auto-mode:adopted-alb-egress',
        `The adopted load balancer's security group (${lbConfig.securityGroupId}) must allow ` +
          `egress to the task security group on port ${this.config.containerPort}. ` +
          'Without it, health checks fail and tasks are killed with exit code 137.',
      );
    }

    const health = this.config.healthCheck;
    const targetGroup = new elbv2.ApplicationTargetGroup(this, 'TargetGroup', {
      vpc,
      port: this.config.containerPort,
      protocol: elbv2.ApplicationProtocol.HTTP,
      targetType: elbv2.TargetType.IP,
      deregistrationDelay: cdk.Duration.seconds(30),
      healthCheck:
        health.type === 'http'
          ? {
              path: health.path,
              healthyThresholdCount: health.healthyThresholdCount ?? 2,
              interval: cdk.Duration.seconds(health.interval ?? 30),
            }
          : {
              // A TCP check: the target group still connects, it just doesn't
              // expect an HTTP response.
              protocol: elbv2.Protocol.TCP,
              healthyThresholdCount: health.healthyThresholdCount ?? 2,
              interval: cdk.Duration.seconds(health.interval ?? 30),
            },
    });

    // An adopted listener is shared, so routing needs a condition — without one it
    // either fails to attach or takes over another service's traffic.
    if (lbConfig.mode === 'adopt' && lbConfig.listenerRuleHostHeader) {
      new elbv2.ApplicationListenerRule(this, 'ListenerRule', {
        listener,
        priority: 100,
        conditions: [elbv2.ListenerCondition.hostHeaders([lbConfig.listenerRuleHostHeader])],
        targetGroups: [targetGroup],
      });
    } else if (lbConfig.mode === 'create') {
      listener.addTargetGroups('Default', { targetGroups: [targetGroup] });
    }

    return targetGroup;
  }

  private buildDnsRecord(alb: elbv2.ApplicationLoadBalancer): void {
    const { hostname, hostedZoneId, zoneName } = this.config.publicHostname!;
    const zone = route53.HostedZone.fromHostedZoneAttributes(this, 'HostedZone', {
      hostedZoneId,
      zoneName,
    });
    new route53.ARecord(this, 'AliasRecord', {
      zone,
      recordName: hostname,
      target: route53.RecordTarget.fromAlias(new targets.LoadBalancerTarget(alb)),
    });
  }

  // ------------------------------------------------------------- pipeline OIDC

  /**
   * Wired only for the github-actions pipeline target — CodePipeline authenticates
   * through a CodeStar connection instead and needs no OIDC role. Previously this
   * wiring lived outside the shipped templates entirely, hand-authored per app,
   * which is how a hardcoded bootstrap qualifier and a non-EMU trust pattern each
   * shipped without a template to diverge from.
   */
  private buildGitHubOidcRole(refs: { taskRole: iam.IRole; executionRole: iam.IRole }): void {
    if (!this.githubActions) return;

    new GitHubOidcRole(this, 'GitHubOidcRole', {
      appName: this.config.name,
      account: this.account,
      region: this.region,
      ssmPrefix: this.config.ssmPrefix,
      cdkQualifier: this.config.cdkQualifier,
      repositoryArn: this.repository.repositoryArn,
      clusterName: this.cluster.clusterName,
      taskRoleArn: refs.taskRole.roleArn,
      executionRoleArn: refs.executionRole.roleArn,
      repository: this.githubActions.repository,
      branch: this.githubActions.branch,
      existingProviderArn: this.githubActions.existingProviderArn,
    });
  }

  // ---------------------------------------------------- platform → service SSM

  /**
   * The contract with the service stack. SSM rather than CloudFormation exports, so
   * the two stacks deploy on completely independent cadences and the service stack
   * can deploy in a pipeline that has never synthesized this one.
   */
  private publishParameters(refs: {
    logGroup: logs.ILogGroup;
    taskSecurityGroup: ec2.ISecurityGroup;
    executionRole: iam.IRole;
    taskRole: iam.IRole;
    targetGroup?: elbv2.IApplicationTargetGroup;
  }): void {
    const prefix = this.config.ssmPrefix;

    const put = (name: string, value: string) => {
      new ssm.StringParameter(this, `Param${pascal(name)}`, {
        parameterName: `${prefix}/${name}`,
        stringValue: value,
      });
    };

    put('cluster-name', this.cluster.clusterName);
    put('cluster-arn', this.cluster.clusterArn);
    put('vpc-id', this.vpc.vpcId);
    put('subnet-ids', this.vpc.selectSubnets(this.appSubnets).subnetIds.join(','));
    put('task-security-group-id', refs.taskSecurityGroup.securityGroupId);
    put('repository-uri', this.repository.repositoryUri);
    put('repository-arn', this.repository.repositoryArn);
    put('log-group-name', refs.logGroup.logGroupName);
    put('execution-role-arn', refs.executionRole.roleArn);
    put('task-role-arn', refs.taskRole.roleArn);

    if (refs.targetGroup) {
      put('target-group-arn', refs.targetGroup.targetGroupArn);
    }
  }
}

function pascal(value: string): string {
  return value.replace(/(^|[-_/])([a-z0-9])/g, (_m, _sep, ch: string) => ch.toUpperCase());
}

function retentionDays(days: number): logs.RetentionDays {
  const byValue = Object.entries(logs.RetentionDays).find(([, v]) => v === days);
  return (byValue?.[1] as logs.RetentionDays) ?? logs.RetentionDays.ONE_MONTH;
}
