#!/usr/bin/env node
// GENERATED by ecs-truly-auto-mode from .ecs-auto-mode/manifest.yaml
// Controlled by: app, target
//
// The projen-layout twin of ../../cdk/bin/app.ts. The only difference is the import
// paths: projen keeps everything under src/, so these are siblings rather than
// `../lib/*`. Any change to one file belongs in the other, and
// `npm run verify:styles` fails if they drift.
//
// Two stacks, deployed on different cadences:
//
//   <name>-platform   rarely — networking, cluster, registry, load balancer, roles
//   <name>-service    every deploy — task definition and service only
//
// They are coupled through SSM Parameter Store, so the service stack can be
// deployed by a pipeline that never synthesizes the platform stack.

import * as cdk from 'aws-cdk-lib';
import { PlatformStack } from './platform-stack';
import { ServiceStack } from './service-stack';
import { config } from './app-config';

const app = new cdk.App();
const env = { account: config.env.account, region: config.env.region };

new PlatformStack(app, `${config.name}-platform`, {
  env,
  config,
  description: `Long-lived platform resources for ${config.name} (ecs-truly-auto-mode)`,
});

new ServiceStack(app, `${config.name}-service`, {
  env,
  config,
  description: `Task definition and service for ${config.name} (ecs-truly-auto-mode)`,
});

cdk.Tags.of(app).add('ManagedBy', 'ecs-truly-auto-mode');
cdk.Tags.of(app).add('Application', config.name);

app.synth();
